on:
  push:
    branches:
      - master
  schedule:
    - cron: "15 3 * * 1" # Every monday at 3:15 AM

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache shards
        uses: actions/cache@v2
        with:
          path: ~/.cache/shards
          key: ${{ runner.os }}-shards-${{ hashFiles('shard.yml') }}
          restore-keys: ${{ runner.os }}-shards-
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
          bundler-cache: true
      - name: Run tests
        run: ./test.sh
